/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.netology.pyas;

import java.util.Arrays;
import java.util.Comparator;
import java.util.List;
import java.util.stream.Collector;
import java.util.stream.Collectors;

import com.google.common.base.Function;

public class Main {

    private final static String TEXT = """
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut sit amet lectus risus. Praesent nec sapien libero. Etiam quam massa, bibendum sit amet imperdiet ac, sagittis vitae mauris. Quisque a ex porta diam lobortis posuere. Integer vitae lorem sed magna ornare porttitor at viverra purus. Cras at neque quis eros aliquet malesuada. Nulla ut ornare dui, nec vehicula metus. Nunc at nunc vel odio gravida tincidunt. Pellentesque suscipit tincidunt nibh. Pellentesque quis erat lacus. Duis iaculis auctor mauris id consectetur. Aenean dui lacus, hendrerit vel felis ac, placerat hendrerit lorem.
        Etiam facilisis dapibus dui a lobortis. Nullam commodo et lectus a ultricies. Morbi accumsan aliquet orci tincidunt finibus. Nullam blandit dignissim interdum. Fusce faucibus in est non venenatis. Aliquam id vestibulum mauris. Pellentesque porta ante sit amet odio mollis, eget blandit magna commodo. Fusce facilisis cursus elit ac sollicitudin. Mauris lobortis vel odio at porta. Vestibulum fringilla, nisl et sodales convallis, lacus libero dignissim nisi, sit amet volutpat sapien velit quis neque. Praesent ac mi nulla. Fusce turpis risus, ultrices vitae feugiat ultrices, ultricies nec lorem.
        Aliquam suscipit risus non augue tristique, a ullamcorper sapien consequat. Nulla feugiat consectetur nisi sit amet pellentesque. Aenean ullamcorper sed magna vitae bibendum. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur ipsum sem, luctus vitae efficitur nec, condimentum eu justo. Aenean felis nunc, condimentum ac mauris nec, luctus cursus orci. Phasellus sagittis dui et mattis maximus. In consequat cursus sapien non gravida. Aenean commodo sem eros, a pharetra elit vestibulum id. Aliquam egestas, erat eget ullamcorper vulputate, ex nunc elementum neque, in iaculis magna orci at sapien. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque a iaculis nibh. Donec ullamcorper purus libero, ut condimentum massa dapibus vel. Curabitur nec iaculis nisi. Pellentesque ex sapien, scelerisque finibus dolor at, feugiat ultricies libero.
    """;

    public static void main(String[] args) {
        Function<String, List<String>> makeDictionary = text -> Arrays.stream(text.split("\\W+"))
            .map(word -> word.toLowerCase())
            .distinct()
            .sorted(Comparator.naturalOrder())
            .collect(Collectors.toList());

        List<String> dictionary = makeDictionary.apply(TEXT);

        dictionary.stream().forEach(System.out::println);
    }
}
